In [1]:
import pandas as pd
import matplotlib.pylab as plt

In [2]:
filename = "./automobile.csv"

In [3]:
headers = ["symboling","normalized-losses","make","fuel-type","aspiration", "num-of-doors","body-style",
         "drive-wheels","engine-location","wheel-base", "length","width","height","curb-weight","engine-type",
         "num-of-cylinders", "engine-size","fuel-system","bore","stroke","compression-ratio","horsepower",
         "peak-rpm","city-mpg","highway-mpg","price"]

In [4]:
#creating a dataset with the headers I specified before
df = pd.read_csv(filename, names = headers)

In [5]:
df.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
2,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
3,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
4,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950

In [6]:
import numpy as np

In [7]:
df.replace('?', np.nan, inplace = True)

In [8]:
df.head(5)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
2,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
3,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
4,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950

In [9]:
missing_data = df.isnull()

In [10]:
missing_data.head(5)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [11]:
for column in missing_data.columns.values.tolist():
    print(column)
    print(missing_data[column].value_counts())
    print("")

symboling
False    206
Name: symboling, dtype: int64

normalized-losses
False    165
True      41
Name: normalized-losses, dtype: int64

make
False    206
Name: make, dtype: int64

fuel-type
False    206
Name: fuel-type, dtype: int64

aspiration
False    206
Name: aspiration, dtype: int64

num-of-doors
False    204
True       2
Name: num-of-doors, dtype: int64

body-style
False    206
Name: body-style, dtype: int64

drive-wheels
False    206
Name: drive-wheels, dtype: int64

engine-location
False    206
Name: engine-location, dtype: int64

wheel-base
False    206
Name: wheel-base, dtype: int64

length
False    206
Name: length, dtype: int64

width
False    206
Name: width, dtype: int64

height
False    206
Name: height, dtype: int64

curb-weight
False    206
Name: curb-weight, dtype: int64

engine-type
False    206
Name: engine-type, dtype: int64

num-of-cylinders
False    206
Name: num-of-cylinders, dtype: int64

engine-size
False    206
Name: engine-size, dtype: int64

fuel-system
False    206
Name: fuel-system, dtype: int64

bore
False    202
True       4
Name: bore, dtype: int64

stroke
False    202
True       4
Name: stroke, dtype: int64

compression-ratio
False    206
Name: compression-ratio, dtype: int64

horsepower
False    204
True       2
Name: horsepower, dtype: int64

peak-rpm
False    204
True       2
Name: peak-rpm, dtype: int64

city-mpg
False    206
Name: city-mpg, dtype: int64

highway-mpg
False    206
Name: highway-mpg, dtype: int64

price
False    202
True       4
Name: price, dtype: int64